### PR TITLE
Generate minified scripts in development environment

### PR DESCRIPTION
**Pull request by alferov**
If you'd like to turn it off - just toggle this value:
https://github.com/alferov/dragular/blob/dev/gulpfile.js#L230

### CODE REVIEW

**Comment by alferov** [comment]
Hey @luckylooke, any updates on this one?

**Comment by luckylooke** [comment]
Sorry, I havent noticed, somehow pull request dont notify me on email. Which value I can toggle? Line 230 doesnt seem to be the one you want to pointed me. Thank you!

**Comment by alferov** [comment]
Oops, sorry, these are #223 and #233:
https://github.com/alferov/dragular/blob/dev/gulpfile.js#L223
https://github.com/alferov/dragular/blob/dev/gulpfile.js#L233

**Comment by luckylooke** [comment]
Can I set it from terminal? Like ```gulp build --isProd``` o something like that? Or I need to edit gulpfile.js?

**Comment by alferov** [comment]
> Can I set it from terminal?

That would be pretty neat, for example:
`gulp build` - produces both minified and non-minified scripts, doesn't trigger watch task
`gulp dev --is-prod` & `gulp watch:docs --is-prod` - triggers watch task, minifies scripts depending on passed flag
`gulp deploy:docs` - runs `gulp build` before being executed

We could also set up git hooks using https://github.com/typicode/husky and run `gulp build` before every commit (so it'd be impossible to skip minification)

**Comment by luckylooke** [comment]
Yes "husky" seems to be very good tool for me as I often forget build before commit :D But generally, developing and testing cycle on production files seems to be better solution. Because some problems can occur after minification. I have noticed sourcemaps, so it should be easy to debug on production files too. Size of project is so small that generating production files is in ms, and so acceptable for developing cycle.

So I suggest to have just 3 main tasks:
`gulp build`  - produces both minified and non-minified scripts, doesn't trigger watch task
`gulp dev` = `gulp dev --is-prod` + `gulp watch:docs --is-prod`
and `gulp deploy` = `gulp deploy:docs` - runs gulp build before being executed

**Comment by alferov** [comment]
Sounds good!

**Pull request merged**
