### PR TITLE
Allow passing a callback function instead of a reference in the containersModel option

### PR DESCRIPTION
**Pull request by aubm**
Hello, regarding to #46 I had something like this in mind :)

### CODE REVIEW

**Comment by davinkevin** [comment]
This is working in my env. We can use this callback to follow the real reference even if it's replaced by another (Like in #46, after a remote call). Very usefull.

**Comment by luckylooke** [comment]
Thanks for contribution :+1:

**Comment by 625alex** [comment]
@luckylooke Is there a change this PL will make it into the master branch?

Thanks!

**Comment by luckylooke** [comment]
@625alex thanks for notifying me, it is really missing in docs. I will put it there ;)

**Pull request merged**
