### PR TITLE
Merging 2.0.0

### PR DESCRIPTION
**Pull request by luckylooke**

### CODE REVIEW

**Comment by alferov** [comment]
Oh, there was no notification for your last message in this thread. Agreed, linting script on the fly would be much better.
What IDE do you use? There are some plugins, like [linter-jshint](https://github.com/AtomLinter/linter-jshint) for atom, that highlight errors during working process!

**Comment by luckylooke** [comment]
I am using sublime text build 3083 :)

**Comment by alferov** [comment]
I found [SublimeLinter-jshint](https://github.com/SublimeLinter/SublimeLinter-jshint). Not sure if it's up to date though. Personally, I use [atom](https://github.com/atom/atom) + [linter-jshint](https://github.com/AtomLinter/linter-jshint). It's awesome to work in isomorphic JavaScript ecosystem, despite the fact that atom is terrible slow with large files :laughing:

**Comment by luckylooke** [comment]
I am used to sublime... maybe one day I will try atom. But I will try
sublime linter soon.. thanks ;-)

**Pull request merged**
