### PR TITLE
Add markdown to html compilation task

### PR DESCRIPTION
**Pull request by alferov**
Hey!
I added `gulp markdown` task that compiles `CONTRIBUTING.md` and `readme.markdown` to `docs/src/examples/partials/partial-contribute.html` and `docs/src/examples/partials/partial-readme.html`. I also added these `.md` files to the watch task: every time when it's changed, it's compiled to html and added to angular template cache.

### CODE REVIEW

**Comment by luckylooke** [comment]
hmm... I would like to have docs similar to angular one, where feature is explained and demo is bellow it. How can this help? Having 16+ demos loaded at once seems not to be good idea so I wanted to chunk it into bits. Also for editing its better, you dont need to search one giant file. Whats your opinion?  :)

**Comment by alferov** [comment]
Oh, I thought I'd like to compile markdown files to html on the fly. As I know angular docs are generated with [dgeni](https://github.com/angular/dgeni). Seems it allows to generate code examples from source but I've never used it, so I'm not 100% sure.
So you'd like to load only one piece per time? Like AMD loaders like RequireJS do?

**Comment by alferov** [comment]
What about #23? I can fix this PR to convert & watch for `contributing.md` only.

**Comment by luckylooke** [comment]
I know angular has generated doc.. We dont need to have generated docs
right now. I just wanted to point on structure of docs. They dont load all
api and exmples on one page. And I think it is more mobile friendly and
better for maintenance. So I want to restructure api from readme into many
small pages. One per feature and with live example. We have examples
already done. We just need to put correct api text to them.

**Comment by luckylooke** [comment]
Yes. Contributing file can be done this way ;-)

**Comment by alferov** [comment]
> api from readme into many small pages

:+1: 
Now I get it. It could be done manually then.

Oh, I've got an idea: using angular-material instead of bootstrap.
https://material.angularjs.org/latest/#/
Looks like an appropriate package for the docs.

**Comment by luckylooke** [comment]
You can change it from bootstrap to google-material if you want. ;-) And
yes it is like copypasting work with some edits and so.. thats why it will
take some time.   But it can be done feature by feature.. we dont need to
make it at once.

**Comment by alferov** [comment]
Yeah, it might be boring, but totally doable.

I'm going to open another PR, rebasing this one might lead to merging conflicts with `dev`

**Comment by luckylooke** [comment]
OK

**Pull request closed without merging**
