### PR TITLE
Gulp integration #2

### PR DESCRIPTION
**Pull request by alferov**
Hey, I've nearly finished gulp integration (except testing part, I'll add it when I start writing test).
The following features were added: 
- Browser Sync
- Linting
- Sourcemaps

I've got an idea about source code organizing: 
1. Create a `src` folder at the root level, put `dragular.js` and `dragular.styl` in it
2. Move everything documentation-related to the `documentation` folder
3. Add special gulp task that serves files from `documentation` with browser sync and processes assets.
4. Create another task that automatically pushes files from that folder to `gh-pages`
?????
PROFIT!
:joy:

I can make a PR if you are interested.

### CODE REVIEW

**Comment by luckylooke** [comment]
Of course I am interested ;) I am really glad you are making workflow better, it helps me faster deliver for bugfixes and features.

I was also wondering if code can be spited into multiple files, because it is quite robust. And also it is not very clearly written. So contributing for others must be pain. I dont have such time reserve to do it now, so maybe in future I will split it into browserify modules. Problem would be also find out good and clear structure.

Thank you for contributing ;)

**Comment by alferov** [comment]
Thanks!
Let's do it right. :+1:

**Comment by luckylooke** [comment]
I need to refactor examples site, so I was trying to change gulpfile, but I am not used to work with browserify. Could you please change gulpfile for me? Changes needed:
- follow new structure (see structure bellow list)
- remove stylus and nib (we dont need it for 5 simple rules, and examples are written in pure css anyway)
- setup concatination and sourcemaps for examples files
- put angular template cache and cache all examples views from examples subfolders

New structure:
src/
  dragular/
    dragularSource.js
    dragularSource.css
  examples/
    examplesApp.js
    examplesApp.css
    exampleBasic/
      exampleBasic.js
      exampleBasic.css
      exampleBasic.html
    exampleXY/
      exampleXY.js
      exampleXY.css
      exampleXY.html
    ...
    other examples folders
    ...
dist/
  dragular.js
  dragular.min.js
  dragular.css
  dragular.min.css
  examples/
    examples.js
    examples.css
  index.html

I will divide code and put it to corresponding folders/files... if you have any improvements to my suggestions.. I am open to change/add it ;)

**Comment by alferov** [comment]
@luckylooke, :ok_hand:
I have a suggestion about doc files organizing. Maybe instead of putting docs files in both `dist` and `src` folders, create separate folder that intended to store only documentation.
For example: 
```
src/
  dragular/
    dragularSourceService.js
    dragularSourceDirective.js
    dragularSource.css
dist/
  dragular.js
  dragular.min.js
  dragular.css
  dragular.min.css
docs/
  index.html
  src/
     vendor/
       ------
       theme files
       ------
     examples/
       examplesApp.js
       examplesApp.css
       exampleBasic/
          exampleBasic.js
          exampleBasic.css
          exampleBasic.html
       exampleXY/
          exampleXY.js
          exampleXY.css
          exampleXY.html
  dist/
     examples.js
     examples.css
```
Using this approach we can easily push everything from `docs` to `gh-pages` using [gulp-gh-pages](https://github.com/shinnn/gulp-gh-pages). That directory might contain its own `gulpfile.js` for documentation processing only. As a result, source and documentation are 2 independent modules. What do you think?

**Comment by luckylooke** [comment]
Great.. can be done your structure.. i like it. Just prepare gulp files. I
have splited examples already done. Thanks ;-)

**Comment by alferov** [comment]
Cool!
Could you create a branch and push these splitted files to it when you are ready? I'll finish the process then.
I'm asking about this, because I'm not sure about the way of serving js files (it would be two process - one for the source and another one for documentation). With existing structure it would be much easier to figure it out. Thank you!

**Comment by luckylooke** [comment]
Ok.. but I am on vacation now so if the wheather will be good I wont have
time for it until wednesday. ;-)

**Comment by alferov** [comment]
Okay, It can wait, I'll start working on tests then.
Have a great vacation! :boat:

**Comment by luckylooke** [comment]
[Here it is](https://github.com/luckylooke/dragular/tree/restructure), loading examples are not finished yet but they are splitted into files and folders. Also dragular directive and service are splitted so you need to concat them too in build ;)

**Comment by alferov** [comment]
@luckylooke, thanks for letting me know. I've almost done with browserifying ([branch](https://github.com/alferov/dragular/tree/patch-1)). Only a few things left to do (refactoring mostly). I'll make a PR, once I finish it.

**Comment by luckylooke** [comment]
Ok, I am looking forward ;-)

**Pull request merged**
