### PR TITLE
Touchstart and Touchend Support

### PR DESCRIPTION
**Pull request by ericnograles**
Hey there!

First off, fantastic library, we'd been using this for a project and it was working great!

We did notice that touch events were all janky (fire up Chrome Web Dev and go to mobile dev mode using, say, an iPad). Specifically, X and Y coordinates were not getting returned properly because those properties exist in the .touches collection of a touchstart. As a result, the elementBehindCursor would always resolve to our leftmost div on our site (the X and Y coords from getCoords would evaluate as nulls).

I added some code that seems to make it work, and also went ahead and added what looked to be a missing dependency in the package.json (jshint-stylish).

This gets drag-n-drop working for touch devices from what I can tell. Let me know if this code works for you, or if you'd like to discuss further and refine it a bit.

Many thanks again for the great work on Dragular, looking forward to seeing future releases!

~ Eric Nograles

### CODE REVIEW

**Comment by luckylooke** [comment]
I am sorry I was few days away finishing some projects. I didnt have time for dragular. But now I am back, thanks for solving issue. Could you update your PR, so I can merge it? Thanks ;)

**Comment by ericnograles** [comment]
Hi there, thanks for the reply! Certainly, I'll send it over when I've got the conflict resolved.

**Comment by ericnograles** [comment]
Should be all set! You may need to rebuild dragular.min.js with the small change I dropped into getCoord, but otherwise, we're green.

**Comment by luckylooke** [comment]
Ok, thank you very much.. I will merge it soon. :)

**Comment by luckylooke** [comment]
MErged.. I will make release later.. thanks for contribution ;)

**Comment by luckylooke** [comment]
Hi there! We have problem with your change in getCoord.. It fails on touch devices at ``` if (host.type.indexOf('touch') < 0) {``` with error ```Uncaught TypeError: Cannot read property 'indexOf' of undefined```. I cannot find 'type' property in (Touch event object)[https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent]. So I think you were expecting some other object there. Could you look at it? Thanks

**Comment by luckylooke** [comment]
I have made quick fix:
```if (!host.type || host.type.indexOf('touch') < 0) {```
Please check if it didn't brake your usecase, thanks!

**Pull request merged**
