### PR TITLE
Gulp integration

### PR DESCRIPTION
**Pull request by alferov**
Hi there, sorry for the delay.
I've started worked on gulp integration and I've got several questions so far:
1) Do you need livereload support (with Browsersync)?
2) Sourcemaps generation?
3) Separate file for every gulp task?
4) Linting?
5) ES5 vs ES6?
:squirrel:

A few words about workflow: the generation process directly depends on `config.isProd`. `gulp dev` set it to `true`, runs browserify with watchify (and Browsersync, eventually) and generates non-minified js and css files, when `gulp build` generates only minified output. Is there anything you would like to change?

### CODE REVIEW

**Comment by luckylooke** [comment]
1) Livereload is cool, can be used.
2) Sourcemaps yes
3) up to you... I have used to have it in one file
4) Lintning yes, jslint, jshint, eslint .. up to you I dont have preferences
5) ES6 support is also up to you, I am not using ES6 now but I want to learn it one day
Everything else is just fine.. I only ask you to put it in dev branch for testing, I will merge it into master later, ok?

**Comment by luckylooke** [comment]
I was testing gulp workflow today and its working very well.. thank you for contributing ;)

**Comment by alferov** [comment]
@luckylooke, thank you. I'm working on tests integration & things we discussed before (linting, sourcemaps). I'll make a PR, when I'm done. 
Oh, I keep code in ES5 then. We can migrate later.

**Comment by luckylooke** [comment]
Ok, looking forward ;)

**Pull request merged**
